# SSH rule
ConfigRuleSsh:
  Type: AWS::Config::ConfigRule
  Properties:
    ConfigRuleName: Incoming-SSH-Disabled
    Description: Flags security groups that allow SSH from 0.0.0.0/0 or ::/0.
    Source:
      Owner: AWS
      SourceIdentifier: INCOMING_SSH_DISABLED
    Scope:
      ComplianceResourceTypes:
        - AWS::EC2::SecurityGroup

# RDP rule
ConfigRuleRdp:
  Type: AWS::Config::ConfigRule
  Properties:
    ConfigRuleName: Incoming-RDP-Disabled
    Description: Flags security groups that allow RDP from 0.0.0.0/0 or ::/0.
    Source:
      Owner: AWS
      SourceIdentifier: INCOMING_RDP_DISABLED
    Scope:
      ComplianceResourceTypes:
        - AWS::EC2::SecurityGroup

# Remediation for SSH
VpcSgRemediationConfigSsh:
  Type: AWS::Config::RemediationConfiguration
  DependsOn: RemediateOpenSgDoc
  Properties:
    ConfigRuleName: !Ref ConfigRuleSsh
    TargetType: SSM_DOCUMENT
    TargetId: !Ref RemediateOpenSgDoc
    TargetVersion: "1"
    Automatic: true
    MaximumAutomaticAttempts: 1
    RetryAttemptSeconds: 60
    Parameters:
      AutomationAssumeRole:
        StaticValue:
          Values: [ !GetAtt AutomationRole.Arn ]
      SecurityGroupId:
        ResourceValue:
          Value: RESOURCE_ID
      LambdaFnName:
        StaticValue:
          Values: [ !Ref FunctionName ]

# Remediation for RDP
VpcSgRemediationConfigRdp:
  Type: AWS::Config::RemediationConfiguration
  DependsOn: RemediateOpenSgDoc
  Properties:
    ConfigRuleName: !Ref ConfigRuleRdp
    TargetType: SSM_DOCUMENT
    TargetId: !Ref RemediateOpenSgDoc
    TargetVersion: "1"
    Automatic: true
    MaximumAutomaticAttempts: 1
    RetryAttemptSeconds: 60
    Parameters:
      AutomationAssumeRole:
        StaticValue:
          Values: [ !GetAtt AutomationRole.Arn ]
      SecurityGroupId:
        ResourceValue:
          Value: RESOURCE_ID
      LambdaFnName:
        StaticValue:
          Values: [ !Ref FunctionName ]
